const genre = 
[
    {
        route:'/discover',
        title:'All'
    },
    {
        route:'/discover?genre=netflix',
        title:'Netflix'
    },
    {
        route:'/discover?genre=action',
        title:'Action'
    },
    {
        route:'/discover?genre=comedy',
        title:'Comedy'
    },
    {
        route:'/discover?genre=horror',
        title:'Horror'
    },
    {
        route:'/discover?genre=romance',
        title:'Romance'
    },
    {
        route:'/discover?genre=documentary',
        title:'Documentary'
    },
    {
        route:'/discover?genre=drama',
        title:'Drama'
    },
    {
        route:'/discover?genre=animation',
        title:'Animation'
    },
    {
        route:'/discover?genre=Family',
        title:'Family'
    },
    {
        route:'/discover?genre=fantasy',
        title:'Fantasy'
    },
    {
        route:'/discover?genre=mystery',
        title:'Mystery'
    },
    {
        route:'/discover?genre=thriller',
        title:'Thriller'
    },
]

export default genre