const moviesGenre = 
[
    {
        route:'/discover',
        title:'All'
    },
    {
        route:'/discover/movies?genre=action',
        title:'Action'
    },
    {
        route:'/discover/movies?genre=comedy',
        title:'Comedy'
    },
    {
        route:'/discover/movies?genre=horror',
        title:'Horror'
    },
    {
        route:'/discover/movies?genre=romance',
        title:'Romance'
    },
    {
        route:'/discover/movies?genre=documentary',
        title:'Documentary'
    },
    {
        route:'/discover/movies?genre=drama',
        title:'Drama'
    },
    {
        route:'/discover/movies?genre=animation',
        title:'Animation'
    },
    {
        route:'/discover/movies?genre=Family',
        title:'Family'
    },
    {
        route:'/discover/movies?genre=fantasy',
        title:'Fantasy'
    },
    {
        route:'/discover/movies?genre=mystery',
        title:'Mystery'
    },
    {
        route:'/discover/movies?genre=thriller',
        title:'Thriller'
    },
]

export default moviesGenre