const showsGenre = 
[
    {
        route:'/discover',
        title:'All'
    },
    {
        route:'/discover/shows?genre=netflix',
        title:'Netflix'
    },
    {
        route:'/discover/shows?genre=action',
        title:'Action'
    },
    {
        route:'/discover/shows?genre=comedy',
        title:'Comedy'
    },
    {
        route:'/discover/shows?genre=romance',
        title:'Romance'
    },
    {
        route:'/discover/shows?genre=documentary',
        title:'Documentary'
    },
    {
        route:'/discover/shows?genre=drama',
        title:'Drama'
    },
    {
        route:'/discover/shows?genre=animation',
        title:'Animation'
    },
    {
        route:'/discover/shows?genre=Family',
        title:'Family'
    },
    {
        route:'/discover/shows?genre=fantasy',
        title:'Fantasy'
    },
    {
        route:'/discover/shows?genre=mystery',
        title:'Mystery'
    },
    {
        route:'/discover/shows?genre=talk',
        title:'Talk'
    },
    {
        route:'/discover/shows?genre=reality',
        title:'Reality'
    },
]

export default showsGenre